#!/usr/bin/env bash
set -e

# Exclude ourselves from PATH within this script, to avoid recursing
PATH="${PATH/`dirname $0`:/}"

# Call PHP with the given arguments, and a few extra
PHP_ARGS=(
    # Make OpenSSL trust us
    -d "openssl.cafile=$SSL_CERT_FILE" \
    # Make cURL trust us
    -d "curl.cainfo=$SSL_CERT_FILE" \
    # Prepend a script that enables the proxy
    -d "auto_prepend_file=`dirname $0`/prepend.php" \
    # Pass through all other provided arguments
    "$@"
)

if command -v winpty >/dev/null 2>&1; then
    winpty php ${PHP_ARGS[@]}
else
    php ${PHP_ARGS[@]}
fi