#!/usr/bin/env bash
set -e

# Exclude ourselves from PATH within this script, to avoid recursing
PATH="${PATH/`dirname $0`:/}"

# Build a new PHP config that trusts our certificate, and use PHPRC
# to ensure that the next php command uses it.
export PHPRC=`php $(dirname $0)/build-php-config.php`

# Pass everything through to PHP (but now using our tweaked config)
php "$@"