#!/usr/bin/env bash
set -e

# Exclude ourselves from PATH within this script, to avoid recursing
PATH="${PATH/`dirname $0`:/}"

# Call PHP with the given arguments, and a few extra
PHP_ARGS=(
    # Make OpenSSL trust us
    -d "openssl.cafile=$SSL_CERT_FILE" \
    # Make cURL trust us
    -d "curl.cainfo=$SSL_CERT_FILE" \
    # Pass through all other provided arguments
    "$@"
)
php ${PHP_ARGS[@]}